footprint: [[1.675, -0.4], [1.75, -0.3], [1.75, 0.3], [1.675, 0.4], [1.3, 0.3], [-0.2,0.3], [-0.2, -0.3], [1.3, -0.3]]
#Footprint with forks
#footprint: [[1.675, -0.4], [1.75, -0.3], [1.75, 0.3], [1.675, 0.4], [1.3, 0.3], [-0.2, 0.3], [-0.2, 0.1], [0.85, 0.1], [0.85, -0.1], [-0.2, -0.1], [-0.2, -0.3], [1.3, -0.3]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser
  front_laser:
    sensor_frame: $(arg prefix)front_laser_link
    data_type: LaserScan
    topic: $(arg front_scan_topic)
    marking: true
    clearing: true
