mobile_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  rear_wheel: 'hr_recycler_front_wheel_traction_joint'
  front_steer: 'hr_recycler_front_wheel_steer_joint'
  traction_wheel: 'hr_recycler_front_wheel_traction_joint'
  steer_wheel: 'hr_recycler_front_wheel_steer_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 
  # Base frame_id
  base_frame_id: hr_recycler_base_footprint #default: base_footprint
  # Odom frame_id
  odom_frame_id: hr_recycler_odom
  enable_odom_tf: true
  #Falta calcular..
  wheel_separation_h :  1.67         
  wheel_radius : 0.1

steer_controller:
  type: position_controllers/JointPositionController
  joint: hr_recycler_front_wheel_steer_joint
  pid:
    p: 100
    i: 0.01
    d: 0.0
    antiwindup: false
    publish_state: true

traction_controller:
  type: velocity_controllers/JointVelocityController
  joint: hr_recycler_front_wheel_traction_joint
  pid:
    p: 100
    i: 0.01
    d: 0.0
    antiwindup: false
    publish_state: true

elevator_controller:
  type: position_controllers/JointPositionController
  joint: hr_recycler_both_forks_elevator_joint
  pid:
    p: 100
    i: 0.01
    d: 0.0
    antiwindup: false
    publish_state: true


joint_read_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
